// Real exercise images from Wger (CC licensed) - https://wger.de
const WGER = "https://wger.de/media/exercise-images";

// Known exercises catalog – used for selection and reference
export const KNOWN_EXERCISES = [
  // Chest
  { name: "Bench press", category: "Chest", description: "Compound chest exercise targeting pectorals, shoulders, and triceps.", form: "Lie on bench, grip bar slightly wider than shoulders. Lower bar to mid-chest, press up until arms are extended. Keep shoulder blades retracted, feet flat on floor.", imageUrl: `${WGER}/192/Bench-press-1.png`, formImages: [`${WGER}/192/Bench-press-1.png`] },
  { name: "Incline bench press", category: "Chest", description: "Upper chest emphasis.", form: "Set bench to 30–45° incline. Same grip and motion as flat bench. Lower to upper chest, press up.", imageUrl: `${WGER}/16/Incline-press-1.png`, formImages: [`${WGER}/16/Incline-press-1.png`] },
  { name: "Decline bench press", category: "Chest", description: "Lower chest emphasis.", form: "Bench angled down 15–30°. Grip bar, lower to lower chest, press up.", imageUrl: `${WGER}/100/Decline-bench-press-1.png`, formImages: [`${WGER}/100/Decline-bench-press-1.png`] },
  { name: "Dumbbell bench press", category: "Chest", description: "Chest press with greater range of motion and stabilizer activation.", form: "Lie flat, dumbbells at shoulder level. Press up until arms extend, lower with control.", imageUrl: `${WGER}/97/Dumbbell-bench-press-1.png`, formImages: [`${WGER}/97/Dumbbell-bench-press-1.png`] },
  { name: "Incline dumbbell press", category: "Chest", description: "Upper chest with dumbbells.", form: "Bench at 30–45° incline. Press dumbbells from shoulder height to arms extended.", imageUrl: `${WGER}/41/Incline-bench-press-1.png`, formImages: [`${WGER}/41/Incline-bench-press-1.png`] },
  { name: "Cable fly", category: "Chest", description: "Chest isolation.", form: "Cables at shoulder height. Bring handles together in front of chest with slight bend in elbows. Return with control.", imageUrl: `${WGER}/71/Cable-crossover-2.png`, formImages: [`${WGER}/71/Cable-crossover-2.png`] },
  { name: "Incline cable fly", category: "Chest", description: "Upper chest cable isolation.", form: "Cables low, handles at chest height. Bring hands together in an arc above chest.", imageUrl: `${WGER}/122/Incline-cable-flyes-1.png`, formImages: [`${WGER}/122/Incline-cable-flyes-1.png`] },
  { name: "Pec deck", category: "Chest", description: "Machine chest isolation.", form: "Sit at machine, arms out. Bring pads together in front of chest, squeeze and return.", imageUrl: `${WGER}/98/Butterfly-machine-2.png`, formImages: [`${WGER}/98/Butterfly-machine-2.png`] },
  { name: "Push-up", category: "Chest", description: "Bodyweight chest and triceps.", form: "Plank, hands shoulder-width. Lower chest toward floor, elbows ~45°. Push back up.", imageUrl: `${WGER}/192/Bench-press-1.png`, formImages: [`${WGER}/192/Bench-press-1.png`] },
  { name: "Machine chest press", category: "Chest", description: "Machine compound chest press.", form: "Sit, grip handles. Press forward until arms extend. Return with control.", imageUrl: `${WGER}/97/Dumbbell-bench-press-1.png`, formImages: [`${WGER}/97/Dumbbell-bench-press-1.png`] },
  // Back
  { name: "Deadlift", category: "Back", description: "Full-body posterior chain exercise.", form: "Feet hip-width, bar over mid-foot. Hinge at hips, grip bar, chest up. Drive through heels, extend hips and knees together. Don't round lower back.", imageUrl: `${WGER}/161/Dead-lifts-2.png`, formImages: [`${WGER}/161/Dead-lifts-2.png`] },
  { name: "Barbell row", category: "Back", description: "Horizontal pull for back thickness.", form: "Hinge at hips, bar hanging. Pull bar to lower chest/upper abs. Keep back flat, don't use momentum.", imageUrl: `${WGER}/110/Reverse-grip-bent-over-rows-1.png`, formImages: [`${WGER}/110/Reverse-grip-bent-over-rows-1.png`] },
  { name: "Dumbbell row", category: "Back", description: "Unilateral row for balanced development.", form: "Support on bench, one knee and hand. Pull dumbbell to hip, elbow close. Lower with control.", imageUrl: `${WGER}/106/T-bar-row-1.png`, formImages: [`${WGER}/106/T-bar-row-1.png`] },
  { name: "Seated cable row", category: "Back", description: "Machine horizontal pull.", form: "Sit, feet on platform. Pull handle to lower chest, squeeze shoulder blades. Return with control.", imageUrl: `${WGER}/143/Cable-seated-rows-2.png`, formImages: [`${WGER}/143/Cable-seated-rows-2.png`] },
  { name: "Lat pulldown", category: "Back", description: "Vertical pull targeting lats.", form: "Sit, grip bar wide. Pull bar to upper chest, squeeze shoulder blades. Control the return; don't let shoulders shrug.", imageUrl: `${WGER}/181/Chin-ups-2.png`, formImages: [`${WGER}/181/Chin-ups-2.png`] },
  { name: "Pull-up", category: "Back", description: "Bodyweight vertical pull.", form: "Hang from bar, palms away. Pull chest to bar, lower with control. Avoid kipping.", imageUrl: `${WGER}/181/Chin-ups-2.png`, formImages: [`${WGER}/181/Chin-ups-2.png`] },
  { name: "Chin-up", category: "Back", description: "Bodyweight vertical pull with supinated grip, more bicep emphasis.", form: "Hang from bar, palms toward you. Pull chin over bar, lower with control.", imageUrl: `${WGER}/181/Chin-ups-2.png`, formImages: [`${WGER}/181/Chin-ups-2.png`] },
  { name: "Barbell shrug", category: "Back", description: "Trap isolation.", form: "Stand with bar at arms' length. Shrug shoulders up toward ears. Lower with control.", imageUrl: `${WGER}/150/Barbell-shrugs-1.png`, formImages: [`${WGER}/150/Barbell-shrugs-1.png`] },
  { name: "Dumbbell shrug", category: "Back", description: "Unilateral trap isolation.", form: "Dumbbells at sides. Shrug shoulders up, squeeze at top.", imageUrl: `${WGER}/151/Dumbbell-shrugs-2.png`, formImages: [`${WGER}/151/Dumbbell-shrugs-2.png`] },
  // Shoulders
  { name: "Overhead press", category: "Shoulders", description: "Compound shoulder exercise.", form: "Bar at shoulder height, grip just outside shoulders. Press bar overhead until arms lock. Lower with control to shoulders.", imageUrl: `${WGER}/119/seated-barbell-shoulder-press-large-1.png`, formImages: [`${WGER}/119/seated-barbell-shoulder-press-large-1.png`] },
  { name: "Dumbbell shoulder press", category: "Shoulders", description: "Shoulder press with dumbbells for greater ROM.", form: "Dumbbells at shoulder height. Press overhead until arms extend. Lower with control.", imageUrl: `${WGER}/123/dumbbell-shoulder-press-large-1.png`, formImages: [`${WGER}/123/dumbbell-shoulder-press-large-1.png`] },
  { name: "Machine shoulder press", category: "Shoulders", description: "Machine shoulder compound.", form: "Sit, grip handles. Press weight overhead, lower with control.", imageUrl: `${WGER}/53/Shoulder-press-machine-2.png`, formImages: [`${WGER}/53/Shoulder-press-machine-2.png`] },
  { name: "Lateral raise", category: "Shoulders", description: "Lateral delt isolation.", form: "Stand, dumbbells at sides. Raise arms to sides until parallel to floor. Slight bend in elbows, control the descent.", imageUrl: `${WGER}/148/lateral-dumbbell-raises-large-2.png`, formImages: [`${WGER}/148/lateral-dumbbell-raises-large-2.png`] },
  { name: "Face pull", category: "Shoulders", description: "Rear delts and rotator cuff.", form: "Cable at face height, rope attachment. Pull rope to face, elbows high and out. Squeeze shoulder blades.", imageUrl: `${WGER}/109/Barbell-rear-delt-row-1.png`, formImages: [`${WGER}/109/Barbell-rear-delt-row-1.png`] },
  { name: "Cable rear delt fly", category: "Shoulders", description: "Rear delt isolation via cable.", form: "Cables at shoulder height. Pull arms back and out, squeezing rear delts.", imageUrl: `${WGER}/109/Barbell-rear-delt-row-1.png`, formImages: [`${WGER}/109/Barbell-rear-delt-row-1.png`] },
  { name: "Front raise", category: "Shoulders", description: "Anterior delt isolation.", form: "Stand, dumbbells in front of thighs. Raise arms to shoulder height, lower with control.", imageUrl: `${WGER}/148/lateral-dumbbell-raises-large-2.png`, formImages: [`${WGER}/148/lateral-dumbbell-raises-large-2.png`] },
  // Biceps
  { name: "Barbell curl", category: "Biceps", description: "Bicep isolation.", form: "Stand, bar at arms' length. Curl bar to shoulders, elbows at sides. Lower without swinging.", imageUrl: `${WGER}/81/Biceps-curl-1.png`, formImages: [`${WGER}/81/Biceps-curl-1.png`] },
  { name: "Dumbbell curl", category: "Biceps", description: "Bicep isolation with dumbbells.", form: "Stand, dumbbells at sides. Curl to shoulders, elbows at sides. Lower with control.", imageUrl: `${WGER}/74/Bicep-curls-1.png`, formImages: [`${WGER}/74/Bicep-curls-1.png`] },
  { name: "Hammer curl", category: "Biceps", description: "Brachialis and bicep, neutral grip.", form: "Dumbbells at sides, palms in. Curl to shoulders, keep palms facing each other.", imageUrl: `${WGER}/86/Bicep-hammer-curl-1.png`, formImages: [`${WGER}/86/Bicep-hammer-curl-1.png`] },
  { name: "Preacher curl", category: "Biceps", description: "Strict bicep isolation on preacher bench.", form: "Upper arms on pad, bar at arms' length. Curl to shoulders, lower fully.", imageUrl: `${WGER}/193/Preacher-curl-3-1.png`, formImages: [`${WGER}/193/Preacher-curl-3-1.png`] },
  { name: "Cable curl", category: "Biceps", description: "Constant-tension bicep curl.", form: "Cable at bottom, bar or rope. Curl to shoulders, control the descent.", imageUrl: `${WGER}/81/Biceps-curl-1.png`, formImages: [`${WGER}/81/Biceps-curl-1.png`] },
  // Triceps
  { name: "Triceps pushdown", category: "Triceps", description: "Tricep isolation.", form: "Cable at chest height, grip bar or rope. Push down until arms extend. Keep elbows at sides, don't swing.", imageUrl: `${WGER}/84/Lying-close-grip-triceps-press-to-chin-1.png`, formImages: [`${WGER}/84/Lying-close-grip-triceps-press-to-chin-1.png`] },
  { name: "Skull crusher", category: "Triceps", description: "Lying tricep extension.", form: "Lie on bench, bar at arms' length. Lower bar to forehead/ears by bending elbows. Extend arms to return.", imageUrl: `${WGER}/84/Lying-close-grip-triceps-press-to-chin-1.png`, formImages: [`${WGER}/84/Lying-close-grip-triceps-press-to-chin-1.png`] },
  { name: "Close grip bench press", category: "Triceps", description: "Compound tricep and chest.", form: "Grip bar shoulder-width or closer. Lower to chest, press up. Keep elbows tucked.", imageUrl: `${WGER}/61/Close-grip-bench-press-1.png`, formImages: [`${WGER}/61/Close-grip-bench-press-1.png`] },
  { name: "Bench dip", category: "Triceps", description: "Bodyweight tricep dip.", form: "Hands on bench, feet on floor. Lower body by bending elbows, press back up.", imageUrl: `${WGER}/83/Bench-dips-1.png`, formImages: [`${WGER}/83/Bench-dips-1.png`] },
  { name: "Overhead tricep extension", category: "Triceps", description: "Long-head tricep emphasis.", form: "Dumbbell or bar overhead. Lower behind head by bending elbows, extend to return.", imageUrl: `${WGER}/84/Lying-close-grip-triceps-press-to-chin-1.png`, formImages: [`${WGER}/84/Lying-close-grip-triceps-press-to-chin-1.png`] },
  // Legs
  { name: "Squat", category: "Legs", description: "Compound leg exercise targeting quads, glutes, hamstrings.", form: "Bar on upper back, feet shoulder-width. Descend by bending knees and hips until thighs are at least parallel. Drive through heels to stand.", imageUrl: `${WGER}/130/Narrow-stance-hack-squats-1-1024x721.png`, formImages: [`${WGER}/130/Narrow-stance-hack-squats-1-1024x721.png`] },
  { name: "Front squat", category: "Legs", description: "Quad-dominant squat with bar in front.", form: "Bar on front delts, elbows high. Descend as in back squat, drive through heels.", imageUrl: `${WGER}/191/Front-squat-1-857x1024.png`, formImages: [`${WGER}/191/Front-squat-1-857x1024.png`] },
  { name: "Leg press", category: "Legs", description: "Machine compound leg exercise.", form: "Feet shoulder-width on platform. Lower weight by bending knees, press back up. Don't lock knees at top.", imageUrl: `${WGER}/130/Narrow-stance-hack-squats-1-1024x721.png`, formImages: [`${WGER}/130/Narrow-stance-hack-squats-1-1024x721.png`] },
  { name: "Romanian deadlift", category: "Legs", description: "Hamstring and hip hinge.", form: "Slight knee bend, hinge at hips. Lower bar along legs until hamstrings stretch. Drive hips forward to stand.", imageUrl: `${WGER}/116/Good-mornings-2.png`, formImages: [`${WGER}/116/Good-mornings-2.png`] },
  { name: "Leg curl", category: "Legs", description: "Hamstring isolation.", form: "Lie or sit on machine, heels under pad. Curl weight toward glutes. Lower with control.", imageUrl: `${WGER}/154/lying-leg-curl-machine-large-1.png`, formImages: [`${WGER}/154/lying-leg-curl-machine-large-1.png`] },
  { name: "Seated leg curl", category: "Legs", description: "Hamstring isolation, seated.", form: "Sit, shins under pad. Curl weight toward seat. Lower with control.", imageUrl: `${WGER}/117/seated-leg-curl-large-1.png`, formImages: [`${WGER}/117/seated-leg-curl-large-1.png`] },
  { name: "Leg extension", category: "Legs", description: "Quad isolation.", form: "Sit, shins under pad. Extend legs until straight. Lower with control; avoid locking at top.", imageUrl: `${WGER}/130/Narrow-stance-hack-squats-1-1024x721.png`, formImages: [`${WGER}/130/Narrow-stance-hack-squats-1-1024x721.png`] },
  { name: "Calf raise", category: "Legs", description: "Calf isolation.", form: "Stand on edge of step, balls of feet. Rise onto toes, lower heels below step level. Full range of motion.", imageUrl: `${WGER}/113/Walking-lunges-1.png`, formImages: [`${WGER}/113/Walking-lunges-1.png`] },
  { name: "Walking lunge", category: "Legs", description: "Unilateral leg exercise.", form: "Step forward, lower back knee toward floor. Drive through front leg to stand, repeat on other leg.", imageUrl: `${WGER}/113/Walking-lunges-1.png`, formImages: [`${WGER}/113/Walking-lunges-1.png`] },
  { name: "Bulgarian split squat", category: "Legs", description: "Unilateral quad and glute emphasis.", form: "Rear foot on bench, front foot forward. Lower until front thigh is parallel, drive up.", imageUrl: `${WGER}/113/Walking-lunges-1.png`, formImages: [`${WGER}/113/Walking-lunges-1.png`] },
  { name: "Hip thrust", category: "Legs", description: "Glute-dominant hip extension.", form: "Upper back on bench, bar across hips. Drive hips up until body is straight. Squeeze glutes at top.", imageUrl: `${WGER}/130/Narrow-stance-hack-squats-1-1024x721.png`, formImages: [`${WGER}/130/Narrow-stance-hack-squats-1-1024x721.png`] },
  { name: "Hack squat", category: "Legs", description: "Machine squat with emphasis on quads.", form: "Back on pad, feet on platform. Lower by bending knees, press back up.", imageUrl: `${WGER}/130/Narrow-stance-hack-squats-1-1024x721.png`, formImages: [`${WGER}/130/Narrow-stance-hack-squats-1-1024x721.png`] },
  { name: "Hip abductor", category: "Legs", description: "Hip abduction targeting gluteus medius and outer hip.", form: "Sit at machine, knees against pads. Push legs outward against resistance. Return with control.", imageUrl: `${WGER}/117/seated-leg-curl-large-1.png`, formImages: [`${WGER}/117/seated-leg-curl-large-1.png`] },
  { name: "Hip adductor", category: "Legs", description: "Hip adduction targeting inner thigh.", form: "Sit at machine, legs on outside of pads. Squeeze legs together against resistance. Return with control.", imageUrl: `${WGER}/117/seated-leg-curl-large-1.png`, formImages: [`${WGER}/117/seated-leg-curl-large-1.png`] },
  // Core / Abs
  { name: "Crunches", category: "Abs", description: "Basic ab isolation.", form: "Lie on back, knees bent. Curl shoulders off floor, lower with control.", imageUrl: `${WGER}/91/Crunches-1.png`, formImages: [`${WGER}/91/Crunches-1.png`] },
  { name: "Decline crunch", category: "Abs", description: "Crunches on decline bench for added resistance.", form: "Feet secured on decline. Curl shoulders toward hips.", imageUrl: `${WGER}/93/Decline-crunch-1.png`, formImages: [`${WGER}/93/Decline-crunch-1.png`] },
  { name: "Leg raise", category: "Abs", description: "Lower ab focus.", form: "Hang or lie flat. Raise legs until perpendicular to floor. Lower with control.", imageUrl: `${WGER}/125/Leg-raises-2.png`, formImages: [`${WGER}/125/Leg-raises-2.png`] },
  { name: "Plank", category: "Abs", description: "Isometric core hold.", form: "Forearms on floor, body straight. Hold position, don't let hips sag.", imageUrl: `${WGER}/91/Crunches-1.png`, formImages: [`${WGER}/91/Crunches-1.png`] },
  { name: "Cable crunch", category: "Abs", description: "Weighted ab crunch.", form: "Kneel at cable, rope at head. Crunch down, contract abs. Return with control.", imageUrl: `${WGER}/91/Crunches-1.png`, formImages: [`${WGER}/91/Crunches-1.png`] },
];
